const wordList = [
    { word: "ocean", hint: "Vast body of saltwater." },
    { word: "breeze", hint: "Gentle wind." },
    { word: "candle", hint: "Wax stick with a wick, used for light." },
    { word: "garden", hint: "Outdoor space for growing plants." },
    { word: "dolphin", hint: "Marine mammal known for its intelligence." },
    { word: "island", hint: "Land surrounded by water on all sides." },
    { word: "firefly", hint: "Insect known for its bioluminescence." },
    { word: "mountain", hint: "Tall natural elevation of land." },
    { word: "whisper", hint: "Speaking softly or quietly." },
    { word: "puzzle", hint: "Game or problem to test knowledge." },
    { word: "guitar", hint: "Stringed musical instrument." },
    { word: "chocolate", hint: "Sweet treat made from cocoa." },
    { word: "river", hint: "Natural flowing watercourse." },
    { word: "rainbow", hint: "Multicolored arc in the sky." },
    { word: "shelter", hint: "Place of protection or refuge." },
    { word: "camera", hint: "Device for capturing images." },
    { word: "journey", hint: "Traveling from one place to another." },
    { word: "library", hint: "Place with books for reading." },
    { word: "oasis", hint: "Fertile spot in a desert." },
    { word: "sandbox", hint: "Container of sand for play." },
    { word: "balloon", hint: "Inflatable object often filled with air or helium." },
    { word: "cottage", hint: "Small cozy house in the countryside." },
    { word: "raindrop", hint: "A single drop of rain." },
    { word: "magnet", hint: "Object that attracts iron or steel." },
    { word: "comedy", hint: "Entertainment meant to be funny." },
    { word: "echo", hint: "Sound reflection off surfaces." },
    { word: "penguin", hint: "Flightless bird from the Southern Hemisphere." },
    { word: "harbor", hint: "Sheltered area for ships." },
    { word: "silence", hint: "Absence of sound." },
    { word: "harmony", hint: "Agreement or pleasing arrangement." },
    { word: "village", hint: "Small community or settlement." },
    { word: "diamond", hint: "Hard, precious gemstone." },
    { word: "adventure", hint: "Exciting journey or experience." },
    { word: "classic", hint: "Timeless and enduring." },
    { word: "captivate", hint: "Fascinate or hold attention." },
    { word: "butterfly", hint: "Colorful insect with wings." },
    { word: "campfire", hint: "Outdoor fire for warmth or cooking." },
    { word: "treasure", hint: "Valuable objects or wealth." },
    { word: "piano", hint: "Musical instrument with keys." },
    { word: "compass", hint: "Navigational tool indicating direction." },
    { word: "novel", hint: "Long fictional story." },
    { word: "fantasy", hint: "Imaginative and unreal." },
    { word: "victory", hint: "Triumphant win or success." },
    { word: "whistle", hint: "High-pitched sound made by blowing air." },
    { word: "jungle", hint: "Thick, tropical forest." },
    { word: "rainforest", hint: "Lush forest with high rainfall." },
    { word: "sculpture", hint: "Three-dimensional art form." },
    { word: "symphony", hint: "Orchestral music composition." },
    { word: "volcano", hint: "Mountain with molten lava." },
    { word: "wonder", hint: "Amazement or awe." },
    { word: "safari", hint: "Wildlife expedition." },
    { word: "blossom", hint: "Flower in bloom." },
    { word: "harvest", hint: "Gathering of crops." },
    { word: "champion", hint: "Winner or top competitor." },
    { word: "dewdrop", hint: "Moisture condensation on surfaces." },
    { word: "freedom", hint: "Independence or liberation." },
    { word: "horizon", hint: "Line where Earth meets the sky." },
    { word: "moonlight", hint: "Light from the moon." },
    { word: "reflection", hint: "Image bounced back from a surface." },
    { word: "majestic", hint: "Grand and impressive." },
    { word: "passion", hint: "Intense enthusiasm or emotion." },
    { word: "sparkle", hint: "Shine with small, bright flashes." },
    { word: "silhouette", hint: "Dark outline against a light background." },
    { word: "serenity", hint: "Peaceful and calm." },
    { word: "tranquil", hint: "Quiet and peaceful." },
    { word: "nostalgia", hint: "Sentimental longing for the past." },
    { word: "melody", hint: "Musical tune or sequence of notes." },
    { word: "inspire", hint: "Evoke creativity or motivation." },
    { word: "journey", hint: "Traveling from one place to another." },
    { word: "glisten", hint: "Shine or sparkle." },
    { word: "whisper", hint: "Speak softly or quietly." },
    { word: "fragrance", hint: "Pleasant scent or aroma." },
    { word: "nostalgia", hint: "Sentimental longing for the past." },
    { word: "marvel", hint: "Astonishment or admiration." },
    { word: "delight", hint: "Great pleasure or joy." },
    { word: "soothe", hint: "Calm or comfort." },
    { word: "serene", hint: "Peaceful and untroubled." },
    { word: "mystery", hint: "Something difficult to understand." },
    { word: "celebrate", hint: "Mark a special occasion with joy." },
    { word: "enchanted", hint: "Magical or delighted." },
    { word: "blossom", hint: "Flower in bloom." },
    { word: "whisper", hint: "Speak softly or quietly." },
    { word: "sparkle", hint: "Shine with small, bright flashes." },
    { word: "harmony", hint: "Agreement or pleasing arrangement." },
    { word: "journey", hint: "Traveling from one place to another." },
    { word: "glisten", hint: "Shine or sparkle." },
    { word: "fragrance", hint: "Pleasant scent or aroma." },
    { word: "twilight", hint: "The soft, dim light before sunrise or after sunset." },
    { word: "enchantment", hint: "Magical charm or fascination." },
    { word: "discover", hint: "To find or learn something new." },
    { word: "courage", hint: "Bravery in the face of fear or difficulty." },
    { word: "reverie", hint: "A daydream or state of being lost in thought." },
    { word: "effortless", hint: "Seeming easy and natural." },
    { word: "whimsical", hint: "Playfully quaint or fanciful." },
    { word: "illuminate", hint: "To light up or make something brighter." },
    { word: "nostalgic", hint: "Evoking feelings of the past." },
    { word: "rhythm", hint: "A pattern of beats in music or movement." },
    { word: "inspiration", hint: "A source of motivation or creative ideas." },
    { word: "vibrant", hint: "Full of energy, brightness, and life." },
    { word: "effervescent", hint: "Bubbling with excitement or enthusiasm." },
    { word: "charisma", hint: "Compelling attractiveness or charm." },
    { word: "tranquility", hint: "Calmness and peacefulness." },
    { word: "melancholy", hint: "A feeling of sadness or pensiveness." },
    { word: "adventure", hint: "An exciting or daring experience." },
    { word: "serendipity", hint: "Finding something wonderful by chance." },
    { word: "infinity", hint: "Endlessness or boundlessness." },
    { word: "reflection", hint: "The image of something in a mirror or water." },
    { word: "silhouette", hint: "The dark outline of an object against a light background." },
    { word: "majestic", hint: "Grand and impressive." },
    { word: "ephemeral", hint: "Lasting for a very short time; transient." },
    { word: "breathe", hint: "Inhale and exhale air." },
    { word: "wanderlust", hint: "A strong desire to travel and explore the world." },
    { word: "daydream", hint: "A series of pleasant thoughts or fantasies." },
    { word: "captivating", hint: "Holding the attention in an enchanting manner." },
    { word: "insight", hint: "A deep understanding or realization." },
];